---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/camel.svg"
    fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=payment&var-version=1"
  labels:
    provider: "fabric8"
    project: "payment"
    version: "1"
    group: "creditcard"
  name: "payment"
spec:
  replicas: 1
  selector:
    matchLabels:
      project: "payment"
      provider: "fabric8"
      group: "creditcard"
  template:
    metadata:
      annotations:
        fabric8.io/iconUrl: "img/icons/camel.svg"
        fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=payment&var-version=1"
      labels:
        provider: "fabric8"
        project: "payment"
        version: "1"
        group: "creditcard"
    spec:
      containers:
      - env:
        - name: "MYSQL_SERVICE_NAME"
          value: "mysql"
        - name: "MYSQL_SERVICE_DATABASE"
          value: "sampledb"
        - name: "MYSQL_SERVICE_USERNAME"
        - name: "MYSQL_SERVICE_PASSWORD"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "creditcard/payment:1"
        imagePullPolicy: "IfNotPresent"
        name: "karaf"
        ports:
        - containerPort: 8181
          name: "intermapper"
          protocol: "TCP"
        - containerPort: 8778
          name: "jolokia"
          protocol: "TCP"
        securityContext:
          privileged: false
